services:
  # ------------------------
  # PHP / Symfony
  # ------------------------
  php:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: ecoride-php
    volumes:
      - ./back-end:/var/www/html

    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://ecoride:ecoride@mysql:3306/ecoride?serverVersion=8.0&charset=utf8mb4"
      MONGODB_URL: "mongodb://mongo_user:mongo_password@mongo:27017/ecoride_mongo?authSource=admin"
    depends_on:
      - mysql
      - mongo

  # ------------------------
  # Nginx backend (Symfony)
  # ------------------------
  web:
    image: nginx:1.29-alpine
    container_name: ecoride-nginx
    ports:
      - "8080:80"
    volumes:
      - ./back-end/public:/var/www/html/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # ------------------------
  # Frontend
  # ------------------------
  frontend:
    image: nginx:1.29-alpine
    container_name: ecoride-frontend
    ports:
      - "3000:80"
    volumes:
      - ./front-end:/usr/share/nginx/html:ro

  # ------------------------
  # MySQL
  # ------------------------
  mysql:
    image: mysql:8.0
    container_name: ecoride-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoride
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # ------------------------
  # PhpMyAdmin
  # ------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    platform: linux/amd64
    container_name: ecoride-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

  # ------------------------
  # MongoDB
  # ------------------------
  mongo:
    image: mongo:6.0
    container_name: ecoride-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: ecoride_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ------------------------
  # Mongo Express
  # ------------------------
  mongo-express:
    image: mongo-express:latest
    platform: linux/amd64
    container_name: ecoride-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
    ports:
      - "8082:8081"
    depends_on:
      - mongo

# ------------------------
# Volumes
# ------------------------
volumes:
  mysql-data:
  mongo-data:
