security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour le login JWT
        login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall pour l'inscription (pas de sécurité ici)
        register:
            pattern: ^/api/user
            stateless: true
            security: false

        # Firewall pour tout le reste de l'API (protégé par JWT)
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        # Public
        - { path: ^/api/user$, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login$, roles: PUBLIC_ACCESS }

        # Autres routes publiques
        - { path: ^/api/trip/search, roles: PUBLIC_ACCESS }
        - { path: ^/api/trip/all, roles: PUBLIC_ACCESS }
        - { path: ^/api/trip/\d+$, roles: PUBLIC_ACCESS }

        # Tout le reste sécurisé
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
